<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE inventario[
    <!ELEMENT inventario (herramitas?,comidas?,materiales?,armadura?)>
  
    <!-- Definición de herramientas -->
    <!ELEMENT herramientas (herramienta*)>
    <!ELEMENT herramienta EMPTY>

    <!ATTLIST herramienta nombre CDATA #REQUIRED>
    <!ATTLIST herramienta material (madera | metal | piedra | oro | diamante) #REQUIRED>
    <!ATTLIST herramienta durabilidad CDATA "100%">
    <!ATTLIST herramienta encantamiento CDATA #IMPLIED>

    <!ELEMENT comidas (comida*)>
    <!ELEMENT comida EMPTY>
    <!ATTLIST comida nombre CDATA #REQUIRED>
    <!ATTLIST comida cantidad NMTOKEN #REQUIRED>

    <!ELEMENT materiales (material*)>
    <!ELEMENT material EMPTY>
    <!ATTLIST material nombre CDATA #REQUIRED>
    <!ATTLIST material cantidad NMTOKEN #REQUIRED>

    <!-- Definición de armadura -->
    <!ELEMENT armadura (casco?, pechera?, pantalones?, botas?)>
    <!ELEMENT casco EMPTY>
    <!ELEMENT pechera EMPTY>
    <!ELEMENT pantalones EMPTY>
    <!ELEMENT botas EMPTY>

    <!ATTLIST casco material (cuero | oro | metal | diamante) #REQUIRED>
    <!ATTLIST casco durabilidad CDATA "100%">
    <!ATTLIST casco encantamiento CDATA #IMPLIED>

    <!ATTLIST pechera material (cuero | oro | metal | diamante | hierro) #REQUIRED>
    <!ATTLIST pechera durabilidad CDATA "100%">
    <!ATTLIST pechera encantamiento CDATA #IMPLIED>

    <!ATTLIST pantalones material (cuero | oro | metal | diamante) #REQUIRED>
    <!ATTLIST pantalones durabilidad CDATA "100%">
    <!ATTLIST pantalones encantamiento CDATA #IMPLIED>

    <!ATTLIST botas material (cuero | oro | metal | diamante) #REQUIRED>
    <!ATTLIST botas durabilidad CDATA "100%">
    <!ATTLIST botas encantamiento CDATA #IMPLIED>
]>


<inventario>
    <herramientas>
        <herramienta nombre="pico" material="metal" durabilidad="70%" encantamiento="toque de seda" />
        <herramienta nombre="pala" material="diamante" />
        <herramienta nombre="espada" material="oro" />
    </herramientas>
    <comidas>
        <comida nombre="bistec" cantidad="64" />
        <comida nombre="zanhaoria" cantidad="1" />
        <comida nombre="tarta de calabaza" cantidad="33" />
    </comidas>
    <materiales>
        <material nombre="piedra" cantidad="64" />
        <material nombre="piedra" cantidad="64" />
        <material nombre="piedra" cantidad="33" />
        <material nombre="tierra" cantidad="64" />
        <material nombre="tierra" cantidad="64" />
        <material nombre="tierra" cantidad="33" />
        <material nombre="arena" cantidad="21" />
    </materiales>
    <armadura>
        <casco material="diamante" durabilidad="65%" />
        <pechera material="hierro" durabilidad="65%" />
        <pantalones material="oro" />
        <botas material="cuero" encantamiento="caida de pluma" />
    </armadura>
</inventario>
<!--
     QUIERO QUE LAS PIEZAS DE ARMADURA Y LAS HERRAMIENTAS TENGAN UNA DURABILIDAD POR DEFECTO DE 100%
    -->
<!--
     QUIERO QUE EL ATRIBUTO MATERIAL DE LAS HERRAMIENTAS SOLO PUEDA SER "MADERA, METAL, PIEDRA, ORO Y
DIAMANTE"
    -->
<!--
     QUIERO QUE EL ATRIBUTO MATERIAL DE LAS ARMADURAS SOLO PUEDA SER "CUERO, ORO, METAL Y DIAMANTE"
    -->
<!--
     QUIERO QUE LOS ELEMENTOS DE LA ARMADURA SOLO PUEDAN SER CASCO, PECHERA, PANTALONES, BOTAS
    -->
<!--
     QUIERO QUE EL ATRIBUTO CANTIDAD NO PUEDA TENER ESPACIOS
    -->
<!-- OJO!!! EL INVENTARIO PUEDE ESTAR VACÍO-->