=== MiguelAngelSanclemente/prueba1xml/PruebasdeXsd/producto.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   

<xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="tipo" type="xs:string"/>
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="stock" type="xs:int"/>
                        </xs:sequence>
                        <!-- Atributo opcional "fragil" -->
                        <xs:attribute name="fragil" type="xs:boolean" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MiguelAngelSanclemente/prueba1xml/PruebasdeXsd/producto.xml
<?xml version="1.0" encoding="UTF-8"?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="producto.xsd">


   <producto fragil="true">
        <nombre>Manzanas</nombre>
        <tipo>Alimento</tipo>
        <precio>150</precio>
        <stock>50</stock>
    </producto>
    <producto fragil="false">
        <nombre>Naranjas</nombre>
        <tipo>Alimento</tipo>
        <precio>200</precio>
        <stock>30</stock>
    </producto>
    <producto fragil="true">
        <nombre>Vasos</nombre>
        <tipo>Hogar</tipo>
        <precio>500</precio>
        <stock>20</stock>
    </producto>
</productos>
